#!/usr/bin/env python3

number_1 = float(input('Enter first number:  '))
operator = input('Enter operator : + - * / :')
number_2 = float(input('Enter second number:  '))
if (operator == '+'):
    result = number_1 + number_2
    print(number_1,operator,number_2,'=',result)
elif (operator =='-'):
    result = number_1 - number_2
    print (number_1,operator,number_2,'=',result)
elif (operator=='*'):
    result = number_1 * number_2
    print (number_1,operator,number_2,'*',result)
elif (operator == '/'):
    result = number_1 / number_2
    print (number_1, operator,number_2, result)
else:
    print ('Error')
