#! /usr/bin/env python3

lines = """MemTotal:        7858500 kB
MemFree:          647000 kB
MemAvailable:    2487576 kB
Buffers:          244416 kB
"""

lines = lines.split("\n")
total_memory = 0
free_memory = 0
available_memory = 0

for line in lines:
    item = line.split(":")
    if len(item) == 1:
        continue

    mem_type = item[0].strip('')
    value = item[1].strip(' kB') # Stripping off the spaces and 'kB's

    if mem_type == 'MemTotal':
      total_memory = int(value) / 1024 # Converting KB to MB
    elif mem_type == 'MemFree':
      free_memory = int(value) / 1024 # Converting KB to MB
    elif mem_type == 'MemAvailable':
      available_memory = int(value) / 1024 # Converting KB to MB

print('Total Memory: ' + str(total_memory) + ' MB')
print('Free Memory: ' + str(free_memory) + ' MB')
print('Available Memory: ' + str(available_memory) + ' MB')
